### ISSUE TITLE
change detection of file to transform on save to type of file instead of file extension 

### ISSUE THREAD

**Issue by joffroy59** [seanliang/JavaPropertiesEditor#5]
save a file which end with properties change to unicode characters but sometime the properties file is not java properties and it should not be change ... 

can you use type of file in sublimetext instead of parsing the filename for matching ".properties" extension

**Comment by henderea** [comment]
I was having my own issue where this package wasn't processing the file when the file gets reverted, so I went ahead and included a fix for this issue in my PR (#7) while I was at it since it was fairly simple.  Until my PR gets merged, you can get my changes by following the manual install instructions from the readme on [henderea/JavaPropertiesEditor](https://github.com/henderea/JavaPropertiesEditor)
